/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class WKHtmlToPdf */

#ifndef _Included_WKHtmlToPdf
#define _Included_WKHtmlToPdf
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     WKHtmlToPdf
 * Method:    convert
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_WKHtmlToPdf_convert
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
