/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_inikolaev_WKHtmlToPdf */

#ifndef _Included_com_github_inikolaev_WKHtmlToPdf
#define _Included_com_github_inikolaev_WKHtmlToPdf
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_inikolaev_WKHtmlToPdf
 * Method:    convert
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_github_inikolaev_WKHtmlToPdf_convert
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
